### ISSUE TITLE
Question: Is it generally useful?

### ISSUE THREAD

**Issue by paulvi** [remote-collab/remote-collab-rest-api#8]
Is it generally useful for OpenVidu projects?
or is it only for some viper product?

Please describe more who should be interested in README, repository metadata.
E.g. give link to viper

**Comment by mithie** [comment]
Hi there. Yes, this is a common repository developed by BMW which can be used for OpenVidu based projects. We're trying to be as generic as possible with the solution so that others may have some benefit from it. VIPER is just our internal project name and stands for "Visual Perceptibility".

I agree with you that we should update our READMEs and project space to give a better overall impression of the project. Will try and update this asap.

**Comment by mithie** [comment]
hope the issue is resolved now. we reorganized the project structure and removed any product specific configuration.

**Comment by paulvi** [comment]
Thanks

README is now better for judging
